modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory
license = "BSD-3-Clause License for Code"
issueTrackerURL = "https://github.com/lemon-slice-studio/Tea-the-Story/issues"
[[mods]] #mandatory
modId = "teastory" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Tea the Story" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tea-the-story"
logoFile = "ts.png" #optional
credits = "Lemon Slice Studio" #optional
authors = "RoitoLeonine, Gloridifice, MalayP" #optional
description = ''' '''
[[dependencies.teastory]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36.1.0,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.teastory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
[[dependencies.teastory]]
modId = "silveroakoutpost"
mandatory = true
versionRange = "[0.3.5-Beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.teastory]]
modId = "jei"
mandatory = false
versionRange = "[7.7.0.98,)"
ordering = "NONE"
side = "BOTH"
