modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="BSD-3-Clause License for Code"
issueTrackerURL=""
[[mods]]
modId="reteastory"
version="${version}"
displayName="Re-Tea the Story"
displayURL=""
logoFile="ts.png"
credits=""
authors=""
description='''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="balm"
type="required"
versionRange="${balm_version_range}"
ordering="NONE"
side="BOTH"